// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaOrdemServico.Data;

#nullable disable

namespace SistemaOrdemServico.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817192532_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("SistemaOrdemServico.Domain.Entities.OrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FuncionarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroOS")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OrdensServico");
                });

            modelBuilder.Entity("SistemaOrdemServico.Domain.Entities.OrdemServico", b =>
                {
                    b.OwnsMany("SistemaOrdemServico.Domain.Entities.HistoricoStatus", "Historico", b1 =>
                        {
                            b1.Property<Guid>("OrdemServicoId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("DataAlteracao")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Observacao")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("StatusAnterior")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("StatusNovo")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OrdemServicoId", "Id");

                            b1.ToTable("HistoricoStatus", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrdemServicoId");
                        });

                    b.Navigation("Historico");
                });
#pragma warning restore 612, 618
        }
    }
}
